# Generated by Django 5.2.18 on 2026-10-07 17:39

import apps.profiles.models
import django.db.models.deletion
import django.db.models.functions.text
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Profile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("display_name", models.CharField(blank=True, max_length=80)),
                ("profession", models.CharField(blank=True, max_length=80)),
                ("bio", models.TextField(blank=True, max_length=1000)),
                ("location", models.CharField(blank=True, max_length=80)),
                ("website", models.URLField(blank=True)),
                ("contact_email", models.EmailField(blank=True, max_length=254)),
                (
                    "avatar",
                    models.ImageField(
                        blank=True, upload_to=apps.profiles.models.upload_avatar
                    ),
                ),
                ("is_published", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="profile",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Link",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("order", models.PositiveIntegerField(default=0)),
                ("title", models.CharField(max_length=80)),
                ("url", models.URLField(max_length=500)),
                (
                    "icon",
                    models.CharField(
                        choices=[
                            ("github", "Github"),
                            ("linkedin", "Linkedin"),
                            ("telegram", "Telegram"),
                            ("instagram", "Instagram"),
                            ("youtube", "Youtube"),
                            ("behance", "Behance"),
                            ("dribbble", "Dribbble"),
                            ("x", "X"),
                            ("email", "Email"),
                            ("website", "Website"),
                        ],
                        default="website",
                        max_length=20,
                    ),
                ),
                ("is_visible", models.BooleanField(default=True)),
                (
                    "profile",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="links",
                        to="profiles.profile",
                    ),
                ),
            ],
            options={
                "ordering": ["order", "id"],
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Project",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("order", models.PositiveIntegerField(default=0)),
                ("title", models.CharField(max_length=100)),
                ("description", models.TextField(blank=True, max_length=2000)),
                (
                    "image",
                    models.ImageField(
                        blank=True, upload_to=apps.profiles.models.upload_project_image
                    ),
                ),
                ("github_url", models.URLField(blank=True, max_length=500)),
                ("demo_url", models.URLField(blank=True, max_length=500)),
                ("technologies", models.JSONField(blank=True, default=list)),
                ("is_featured", models.BooleanField(default=False)),
                (
                    "profile",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="projects",
                        to="profiles.profile",
                    ),
                ),
            ],
            options={
                "ordering": ["order", "id"],
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Skill",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("order", models.PositiveIntegerField(default=0)),
                ("name", models.CharField(max_length=40)),
                (
                    "profile",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="skills",
                        to="profiles.profile",
                    ),
                ),
            ],
            options={
                "ordering": ["order", "id"],
                "abstract": False,
                "constraints": [
                    models.UniqueConstraint(
                        models.F("profile"),
                        django.db.models.functions.text.Lower("name"),
                        name="unique_skill_per_profile_ci",
                    )
                ],
            },
        ),
    ]
