# Generated by Django 5.2.18 on 2026-10-07 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("profiles", "0004_default_blocks_for_existing_profiles"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="theme",
            field=models.CharField(
                choices=[
                    ("minimal", "Минимализм"),
                    ("dark", "Тёмная"),
                    ("developer", "Разработчик"),
                    ("portfolio", "Портфолио"),
                    ("creative", "Креатив"),
                ],
                default="minimal",
                max_length=20,
            ),
        ),
    ]
