# Generated by Django 5.2.18 on 2026-10-07 18:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("profiles", "0005_profile_theme"),
    ]

    operations = [
        migrations.AlterField(
            model_name="block",
            name="type",
            field=models.CharField(
                choices=[
                    ("profile", "Шапка профиля"),
                    ("links", "Ссылки"),
                    ("text", "Текст"),
                    ("projects", "Проекты"),
                    ("skills", "Навыки"),
                    ("contact", "Контакты"),
                    ("experience", "Опыт работы"),
                    ("education", "Образование"),
                    ("languages", "Языки"),
                ],
                max_length=20,
            ),
        ),
        migrations.CreateModel(
            name="Education",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("order", models.PositiveIntegerField(default=0)),
                ("institution", models.CharField(max_length=150)),
                ("degree", models.CharField(blank=True, max_length=100)),
                ("field", models.CharField(blank=True, max_length=100)),
                ("start_year", models.PositiveSmallIntegerField(blank=True, null=True)),
                ("end_year", models.PositiveSmallIntegerField(blank=True, null=True)),
                ("description", models.TextField(blank=True, max_length=1000)),
                (
                    "profile",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="education",
                        to="profiles.profile",
                    ),
                ),
            ],
            options={
                "ordering": ["order", "id"],
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Experience",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("order", models.PositiveIntegerField(default=0)),
                ("position", models.CharField(max_length=100)),
                ("company", models.CharField(max_length=100)),
                ("location", models.CharField(blank=True, max_length=80)),
                ("start_date", models.DateField()),
                ("end_date", models.DateField(blank=True, null=True)),
                ("description", models.TextField(blank=True, max_length=2000)),
                (
                    "profile",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="experience",
                        to="profiles.profile",
                    ),
                ),
            ],
            options={
                "ordering": ["order", "id"],
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="SpokenLanguage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("order", models.PositiveIntegerField(default=0)),
                ("name", models.CharField(max_length=40)),
                (
                    "level",
                    models.CharField(
                        choices=[
                            ("A1", "A1 — начальный"),
                            ("A2", "A2 — элементарный"),
                            ("B1", "B1 — средний"),
                            ("B2", "B2 — выше среднего"),
                            ("C1", "C1 — продвинутый"),
                            ("C2", "C2 — свободный"),
                            ("native", "Родной"),
                        ],
                        max_length=10,
                    ),
                ),
                (
                    "profile",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="languages",
                        to="profiles.profile",
                    ),
                ),
            ],
            options={
                "ordering": ["order", "id"],
                "abstract": False,
            },
        ),
    ]
