/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v1/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["health_retrieve"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["me_retrieve"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/me/links": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description CRUD over the current user's items + bulk reorder. Subclasses set model/serializer/limit. */
        get: operations["me_links_list"];
        put?: never;
        /** @description CRUD over the current user's items + bulk reorder. Subclasses set model/serializer/limit. */
        post: operations["me_links_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/me/links/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** @description CRUD over the current user's items + bulk reorder. Subclasses set model/serializer/limit. */
        delete: operations["me_links_destroy"];
        options?: never;
        head?: never;
        /** @description CRUD over the current user's items + bulk reorder. Subclasses set model/serializer/limit. */
        patch: operations["me_links_partial_update"];
        trace?: never;
    };
    "/api/v1/me/links/reorder": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** @description CRUD over the current user's items + bulk reorder. Subclasses set model/serializer/limit. */
        post: operations["me_links_reorder_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/me/profile": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["me_profile_retrieve"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch: operations["me_profile_partial_update"];
        trace?: never;
    };
    "/api/v1/me/profile/avatar": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put: operations["me_profile_avatar_update"];
        post?: never;
        delete: operations["me_profile_avatar_destroy"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/me/projects": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description CRUD over the current user's items + bulk reorder. Subclasses set model/serializer/limit. */
        get: operations["me_projects_list"];
        put?: never;
        /** @description CRUD over the current user's items + bulk reorder. Subclasses set model/serializer/limit. */
        post: operations["me_projects_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/me/projects/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /** @description CRUD over the current user's items + bulk reorder. Subclasses set model/serializer/limit. */
        put: operations["me_projects_update"];
        post?: never;
        /** @description CRUD over the current user's items + bulk reorder. Subclasses set model/serializer/limit. */
        delete: operations["me_projects_destroy"];
        options?: never;
        head?: never;
        /** @description CRUD over the current user's items + bulk reorder. Subclasses set model/serializer/limit. */
        patch: operations["me_projects_partial_update"];
        trace?: never;
    };
    "/api/v1/me/projects/{id}/image": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /** @description CRUD over the current user's items + bulk reorder. Subclasses set model/serializer/limit. */
        put: operations["me_projects_image_update"];
        post?: never;
        /** @description CRUD over the current user's items + bulk reorder. Subclasses set model/serializer/limit. */
        delete: operations["me_projects_image_destroy"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/me/projects/reorder": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** @description CRUD over the current user's items + bulk reorder. Subclasses set model/serializer/limit. */
        post: operations["me_projects_reorder_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/me/skills": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description CRUD over the current user's items + bulk reorder. Subclasses set model/serializer/limit. */
        get: operations["me_skills_list"];
        put?: never;
        /** @description CRUD over the current user's items + bulk reorder. Subclasses set model/serializer/limit. */
        post: operations["me_skills_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/me/skills/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** @description CRUD over the current user's items + bulk reorder. Subclasses set model/serializer/limit. */
        delete: operations["me_skills_destroy"];
        options?: never;
        head?: never;
        /** @description CRUD over the current user's items + bulk reorder. Subclasses set model/serializer/limit. */
        patch: operations["me_skills_partial_update"];
        trace?: never;
    };
    "/api/v1/me/skills/reorder": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** @description CRUD over the current user's items + bulk reorder. Subclasses set model/serializer/limit. */
        post: operations["me_skills_reorder_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/profiles/{username}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["profiles_retrieve"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /**
         * @description * `github` - Github
         *     * `linkedin` - Linkedin
         *     * `telegram` - Telegram
         *     * `instagram` - Instagram
         *     * `youtube` - Youtube
         *     * `behance` - Behance
         *     * `dribbble` - Dribbble
         *     * `x` - X
         *     * `email` - Email
         *     * `website` - Website
         * @enum {string}
         */
        IconEnum: "github" | "linkedin" | "telegram" | "instagram" | "youtube" | "behance" | "dribbble" | "x" | "email" | "website";
        ImageUpload: {
            /** Format: uri */
            image: string;
        };
        Link: {
            readonly id: number;
            title: string;
            url: string;
            icon?: components["schemas"]["IconEnum"];
            is_visible?: boolean;
            readonly order: number;
        };
        Me: {
            readonly id: number;
            readonly username: string;
            /** Format: email */
            readonly email: string;
            readonly email_verified: boolean;
            /**
             * Дата регистрации
             * Format: date-time
             */
            readonly date_joined: string;
        };
        PatchedLink: {
            readonly id?: number;
            title?: string;
            url?: string;
            icon?: components["schemas"]["IconEnum"];
            is_visible?: boolean;
            readonly order?: number;
        };
        PatchedProfile: {
            readonly username?: string;
            display_name?: string;
            profession?: string;
            bio?: string;
            location?: string;
            website?: string;
            contact_email?: string;
            /** Format: uri */
            readonly avatar?: string | null;
            is_published?: boolean;
        };
        PatchedProject: {
            readonly id?: number;
            title?: string;
            description?: string;
            /** Format: uri */
            readonly image?: string | null;
            github_url?: string;
            demo_url?: string;
            technologies?: string[];
            is_featured?: boolean;
            readonly order?: number;
        };
        PatchedSkill: {
            readonly id?: number;
            name?: string;
            readonly order?: number;
        };
        Profile: {
            readonly username: string;
            display_name?: string;
            profession?: string;
            bio?: string;
            location?: string;
            website?: string;
            contact_email?: string;
            /** Format: uri */
            readonly avatar: string | null;
            is_published?: boolean;
        };
        Project: {
            readonly id: number;
            title: string;
            description?: string;
            /** Format: uri */
            readonly image: string | null;
            github_url?: string;
            demo_url?: string;
            technologies?: string[];
            is_featured?: boolean;
            readonly order: number;
        };
        PublicLink: {
            readonly id: number;
            title: string;
            /** Format: uri */
            url: string;
            icon?: components["schemas"]["IconEnum"];
        };
        PublicProfile: {
            readonly username: string;
            display_name?: string;
            profession?: string;
            bio?: string;
            location?: string;
            website?: string;
            contact_email?: string;
            /** Format: uri */
            readonly avatar: string | null;
            readonly links: components["schemas"]["PublicLink"][];
            readonly projects: components["schemas"]["Project"][];
            readonly skills: string[];
        };
        Reorder: {
            ids: number[];
        };
        Skill: {
            readonly id: number;
            name: string;
            readonly order: number;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    health_retrieve: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
        };
    };
    me_retrieve: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Me"];
                };
            };
        };
    };
    me_links_list: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Link"][];
                };
            };
        };
    };
    me_links_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["Link"];
                "application/x-www-form-urlencoded": components["schemas"]["Link"];
                "multipart/form-data": components["schemas"]["Link"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Link"];
                };
            };
        };
    };
    me_links_destroy: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description A unique integer value identifying this link. */
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description No response body */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    me_links_partial_update: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description A unique integer value identifying this link. */
                id: number;
            };
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["PatchedLink"];
                "application/x-www-form-urlencoded": components["schemas"]["PatchedLink"];
                "multipart/form-data": components["schemas"]["PatchedLink"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Link"];
                };
            };
        };
    };
    me_links_reorder_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["Reorder"];
                "application/x-www-form-urlencoded": components["schemas"]["Reorder"];
                "multipart/form-data": components["schemas"]["Reorder"];
            };
        };
        responses: {
            /** @description No response body */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    me_profile_retrieve: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Profile"];
                };
            };
        };
    };
    me_profile_partial_update: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["PatchedProfile"];
                "application/x-www-form-urlencoded": components["schemas"]["PatchedProfile"];
                "multipart/form-data": components["schemas"]["PatchedProfile"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Profile"];
                };
            };
        };
    };
    me_profile_avatar_update: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "multipart/form-data": components["schemas"]["ImageUpload"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Profile"];
                };
            };
        };
    };
    me_profile_avatar_destroy: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description No response body */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    me_projects_list: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Project"][];
                };
            };
        };
    };
    me_projects_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["Project"];
                "application/x-www-form-urlencoded": components["schemas"]["Project"];
                "multipart/form-data": components["schemas"]["Project"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Project"];
                };
            };
        };
    };
    me_projects_update: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description A unique integer value identifying this project. */
                id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["Project"];
                "application/x-www-form-urlencoded": components["schemas"]["Project"];
                "multipart/form-data": components["schemas"]["Project"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Project"];
                };
            };
        };
    };
    me_projects_destroy: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description A unique integer value identifying this project. */
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description No response body */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    me_projects_partial_update: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description A unique integer value identifying this project. */
                id: number;
            };
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["PatchedProject"];
                "application/x-www-form-urlencoded": components["schemas"]["PatchedProject"];
                "multipart/form-data": components["schemas"]["PatchedProject"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Project"];
                };
            };
        };
    };
    me_projects_image_update: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description A unique integer value identifying this project. */
                id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "multipart/form-data": components["schemas"]["ImageUpload"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Project"];
                };
            };
        };
    };
    me_projects_image_destroy: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description A unique integer value identifying this project. */
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description No response body */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    me_projects_reorder_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["Reorder"];
                "application/x-www-form-urlencoded": components["schemas"]["Reorder"];
                "multipart/form-data": components["schemas"]["Reorder"];
            };
        };
        responses: {
            /** @description No response body */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    me_skills_list: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Skill"][];
                };
            };
        };
    };
    me_skills_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["Skill"];
                "application/x-www-form-urlencoded": components["schemas"]["Skill"];
                "multipart/form-data": components["schemas"]["Skill"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Skill"];
                };
            };
        };
    };
    me_skills_destroy: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description A unique integer value identifying this skill. */
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description No response body */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    me_skills_partial_update: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description A unique integer value identifying this skill. */
                id: number;
            };
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["PatchedSkill"];
                "application/x-www-form-urlencoded": components["schemas"]["PatchedSkill"];
                "multipart/form-data": components["schemas"]["PatchedSkill"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Skill"];
                };
            };
        };
    };
    me_skills_reorder_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["Reorder"];
                "application/x-www-form-urlencoded": components["schemas"]["Reorder"];
                "multipart/form-data": components["schemas"]["Reorder"];
            };
        };
        responses: {
            /** @description No response body */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    profiles_retrieve: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                username: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PublicProfile"];
                };
            };
        };
    };
}
