/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v1/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["health_retrieve"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["me_retrieve"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/me/analytics": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["me_analytics_retrieve"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/me/blocks": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description CRUD over the current user's items + bulk reorder. Subclasses set model/serializer/limit. */
        get: operations["me_blocks_list"];
        put?: never;
        /** @description CRUD over the current user's items + bulk reorder. Subclasses set model/serializer/limit. */
        post: operations["me_blocks_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/me/blocks/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** @description CRUD over the current user's items + bulk reorder. Subclasses set model/serializer/limit. */
        delete: operations["me_blocks_destroy"];
        options?: never;
        head?: never;
        /** @description CRUD over the current user's items + bulk reorder. Subclasses set model/serializer/limit. */
        patch: operations["me_blocks_partial_update"];
        trace?: never;
    };
    "/api/v1/me/blocks/reorder": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** @description CRUD over the current user's items + bulk reorder. Subclasses set model/serializer/limit. */
        post: operations["me_blocks_reorder_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/me/education": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description CRUD over the current user's items + bulk reorder. Subclasses set model/serializer/limit. */
        get: operations["me_education_list"];
        put?: never;
        /** @description CRUD over the current user's items + bulk reorder. Subclasses set model/serializer/limit. */
        post: operations["me_education_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/me/education/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** @description CRUD over the current user's items + bulk reorder. Subclasses set model/serializer/limit. */
        delete: operations["me_education_destroy"];
        options?: never;
        head?: never;
        /** @description CRUD over the current user's items + bulk reorder. Subclasses set model/serializer/limit. */
        patch: operations["me_education_partial_update"];
        trace?: never;
    };
    "/api/v1/me/education/reorder": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** @description CRUD over the current user's items + bulk reorder. Subclasses set model/serializer/limit. */
        post: operations["me_education_reorder_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/me/experience": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description CRUD over the current user's items + bulk reorder. Subclasses set model/serializer/limit. */
        get: operations["me_experience_list"];
        put?: never;
        /** @description CRUD over the current user's items + bulk reorder. Subclasses set model/serializer/limit. */
        post: operations["me_experience_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/me/experience/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** @description CRUD over the current user's items + bulk reorder. Subclasses set model/serializer/limit. */
        delete: operations["me_experience_destroy"];
        options?: never;
        head?: never;
        /** @description CRUD over the current user's items + bulk reorder. Subclasses set model/serializer/limit. */
        patch: operations["me_experience_partial_update"];
        trace?: never;
    };
    "/api/v1/me/experience/reorder": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** @description CRUD over the current user's items + bulk reorder. Subclasses set model/serializer/limit. */
        post: operations["me_experience_reorder_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/me/languages": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description CRUD over the current user's items + bulk reorder. Subclasses set model/serializer/limit. */
        get: operations["me_languages_list"];
        put?: never;
        /** @description CRUD over the current user's items + bulk reorder. Subclasses set model/serializer/limit. */
        post: operations["me_languages_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/me/languages/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** @description CRUD over the current user's items + bulk reorder. Subclasses set model/serializer/limit. */
        delete: operations["me_languages_destroy"];
        options?: never;
        head?: never;
        /** @description CRUD over the current user's items + bulk reorder. Subclasses set model/serializer/limit. */
        patch: operations["me_languages_partial_update"];
        trace?: never;
    };
    "/api/v1/me/languages/reorder": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** @description CRUD over the current user's items + bulk reorder. Subclasses set model/serializer/limit. */
        post: operations["me_languages_reorder_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/me/links": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description CRUD over the current user's items + bulk reorder. Subclasses set model/serializer/limit. */
        get: operations["me_links_list"];
        put?: never;
        /** @description CRUD over the current user's items + bulk reorder. Subclasses set model/serializer/limit. */
        post: operations["me_links_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/me/links/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** @description CRUD over the current user's items + bulk reorder. Subclasses set model/serializer/limit. */
        delete: operations["me_links_destroy"];
        options?: never;
        head?: never;
        /** @description CRUD over the current user's items + bulk reorder. Subclasses set model/serializer/limit. */
        patch: operations["me_links_partial_update"];
        trace?: never;
    };
    "/api/v1/me/links/reorder": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** @description CRUD over the current user's items + bulk reorder. Subclasses set model/serializer/limit. */
        post: operations["me_links_reorder_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/me/profile": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["me_profile_retrieve"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch: operations["me_profile_partial_update"];
        trace?: never;
    };
    "/api/v1/me/profile/avatar": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put: operations["me_profile_avatar_update"];
        post?: never;
        delete: operations["me_profile_avatar_destroy"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/me/projects": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description CRUD over the current user's items + bulk reorder. Subclasses set model/serializer/limit. */
        get: operations["me_projects_list"];
        put?: never;
        /** @description CRUD over the current user's items + bulk reorder. Subclasses set model/serializer/limit. */
        post: operations["me_projects_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/me/projects/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /** @description CRUD over the current user's items + bulk reorder. Subclasses set model/serializer/limit. */
        put: operations["me_projects_update"];
        post?: never;
        /** @description CRUD over the current user's items + bulk reorder. Subclasses set model/serializer/limit. */
        delete: operations["me_projects_destroy"];
        options?: never;
        head?: never;
        /** @description CRUD over the current user's items + bulk reorder. Subclasses set model/serializer/limit. */
        patch: operations["me_projects_partial_update"];
        trace?: never;
    };
    "/api/v1/me/projects/{id}/image": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /** @description CRUD over the current user's items + bulk reorder. Subclasses set model/serializer/limit. */
        put: operations["me_projects_image_update"];
        post?: never;
        /** @description CRUD over the current user's items + bulk reorder. Subclasses set model/serializer/limit. */
        delete: operations["me_projects_image_destroy"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/me/projects/reorder": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** @description CRUD over the current user's items + bulk reorder. Subclasses set model/serializer/limit. */
        post: operations["me_projects_reorder_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/me/skills": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description CRUD over the current user's items + bulk reorder. Subclasses set model/serializer/limit. */
        get: operations["me_skills_list"];
        put?: never;
        /** @description CRUD over the current user's items + bulk reorder. Subclasses set model/serializer/limit. */
        post: operations["me_skills_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/me/skills/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** @description CRUD over the current user's items + bulk reorder. Subclasses set model/serializer/limit. */
        delete: operations["me_skills_destroy"];
        options?: never;
        head?: never;
        /** @description CRUD over the current user's items + bulk reorder. Subclasses set model/serializer/limit. */
        patch: operations["me_skills_partial_update"];
        trace?: never;
    };
    "/api/v1/me/skills/reorder": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** @description CRUD over the current user's items + bulk reorder. Subclasses set model/serializer/limit. */
        post: operations["me_skills_reorder_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/profiles/{username}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["profiles_retrieve"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/track": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** @description Beacon from the public page. Always 204: never reveals whether anything was counted. */
        post: operations["track_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        Block: {
            readonly id: number;
            type: components["schemas"]["BlockTypeEnum"];
            is_visible?: boolean;
            config?: unknown;
            readonly order: number;
        };
        /**
         * @description * `profile` - Шапка профиля
         *     * `links` - Ссылки
         *     * `text` - Текст
         *     * `projects` - Проекты
         *     * `skills` - Навыки
         *     * `contact` - Контакты
         *     * `experience` - Опыт работы
         *     * `education` - Образование
         *     * `languages` - Языки
         * @enum {string}
         */
        BlockTypeEnum: "profile" | "links" | "text" | "projects" | "skills" | "contact" | "experience" | "education" | "languages";
        Education: {
            readonly id: number;
            institution: string;
            degree?: string;
            field?: string;
            start_year?: number | null;
            end_year?: number | null;
            description?: string;
            readonly order: number;
        };
        /**
         * @description * `view` - View
         *     * `click` - Click
         * @enum {string}
         */
        EventTypeEnum: "view" | "click";
        Experience: {
            readonly id: number;
            position: string;
            company: string;
            location?: string;
            /** Format: date */
            start_date: string;
            /** Format: date */
            end_date?: string | null;
            description?: string;
            readonly order: number;
        };
        /**
         * @description * `github` - Github
         *     * `linkedin` - Linkedin
         *     * `telegram` - Telegram
         *     * `instagram` - Instagram
         *     * `youtube` - Youtube
         *     * `behance` - Behance
         *     * `dribbble` - Dribbble
         *     * `x` - X
         *     * `email` - Email
         *     * `website` - Website
         * @enum {string}
         */
        IconEnum: "github" | "linkedin" | "telegram" | "instagram" | "youtube" | "behance" | "dribbble" | "x" | "email" | "website";
        ImageUpload: {
            /** Format: uri */
            image: string;
        };
        /**
         * @description * `A1` - A1 — начальный
         *     * `A2` - A2 — элементарный
         *     * `B1` - B1 — средний
         *     * `B2` - B2 — выше среднего
         *     * `C1` - C1 — продвинутый
         *     * `C2` - C2 — свободный
         *     * `native` - Родной
         * @enum {string}
         */
        LevelEnum: "A1" | "A2" | "B1" | "B2" | "C1" | "C2" | "native";
        Link: {
            readonly id: number;
            title: string;
            url: string;
            icon?: components["schemas"]["IconEnum"];
            is_visible?: boolean;
            readonly order: number;
        };
        Me: {
            readonly id: number;
            readonly username: string;
            /** Format: email */
            readonly email: string;
            readonly email_verified: boolean;
            /**
             * Дата регистрации
             * Format: date-time
             */
            readonly date_joined: string;
        };
        PatchedBlock: {
            readonly id?: number;
            type?: components["schemas"]["BlockTypeEnum"];
            is_visible?: boolean;
            config?: unknown;
            readonly order?: number;
        };
        PatchedEducation: {
            readonly id?: number;
            institution?: string;
            degree?: string;
            field?: string;
            start_year?: number | null;
            end_year?: number | null;
            description?: string;
            readonly order?: number;
        };
        PatchedExperience: {
            readonly id?: number;
            position?: string;
            company?: string;
            location?: string;
            /** Format: date */
            start_date?: string;
            /** Format: date */
            end_date?: string | null;
            description?: string;
            readonly order?: number;
        };
        PatchedLink: {
            readonly id?: number;
            title?: string;
            url?: string;
            icon?: components["schemas"]["IconEnum"];
            is_visible?: boolean;
            readonly order?: number;
        };
        PatchedProfile: {
            readonly username?: string;
            display_name?: string;
            profession?: string;
            bio?: string;
            location?: string;
            website?: string;
            contact_email?: string;
            /** Format: uri */
            readonly avatar?: string | null;
            theme?: components["schemas"]["ThemeEnum"];
            is_published?: boolean;
        };
        PatchedProject: {
            readonly id?: number;
            title?: string;
            description?: string;
            /** Format: uri */
            readonly image?: string | null;
            github_url?: string;
            demo_url?: string;
            technologies?: string[];
            is_featured?: boolean;
            readonly order?: number;
        };
        PatchedSkill: {
            readonly id?: number;
            name?: string;
            readonly order?: number;
        };
        PatchedSpokenLanguage: {
            readonly id?: number;
            name?: string;
            level?: components["schemas"]["LevelEnum"];
            readonly order?: number;
        };
        Profile: {
            readonly username: string;
            display_name?: string;
            profession?: string;
            bio?: string;
            location?: string;
            website?: string;
            contact_email?: string;
            /** Format: uri */
            readonly avatar: string | null;
            theme?: components["schemas"]["ThemeEnum"];
            is_published?: boolean;
        };
        Project: {
            readonly id: number;
            title: string;
            description?: string;
            /** Format: uri */
            readonly image: string | null;
            github_url?: string;
            demo_url?: string;
            technologies?: string[];
            is_featured?: boolean;
            readonly order: number;
        };
        PublicBlock: {
            readonly id: number;
            type: components["schemas"]["BlockTypeEnum"];
            config?: unknown;
        };
        PublicLink: {
            readonly id: number;
            title: string;
            /** Format: uri */
            url: string;
            icon?: components["schemas"]["IconEnum"];
        };
        PublicProfile: {
            readonly username: string;
            display_name?: string;
            profession?: string;
            bio?: string;
            location?: string;
            website?: string;
            contact_email?: string;
            /** Format: uri */
            readonly avatar: string | null;
            theme?: components["schemas"]["ThemeEnum"];
            readonly blocks: components["schemas"]["PublicBlock"][];
            readonly links: components["schemas"]["PublicLink"][];
            readonly projects: components["schemas"]["Project"][];
            readonly skills: string[];
            readonly experience: components["schemas"]["Experience"][];
            readonly education: components["schemas"]["Education"][];
            readonly languages: components["schemas"]["SpokenLanguage"][];
        };
        Reorder: {
            ids: number[];
        };
        Skill: {
            readonly id: number;
            name: string;
            readonly order: number;
        };
        SpokenLanguage: {
            readonly id: number;
            name: string;
            level: components["schemas"]["LevelEnum"];
            readonly order: number;
        };
        /**
         * @description * `minimal` - Минимализм
         *     * `dark` - Тёмная
         *     * `developer` - Разработчик
         *     * `portfolio` - Портфолио
         *     * `creative` - Креатив
         * @enum {string}
         */
        ThemeEnum: "minimal" | "dark" | "developer" | "portfolio" | "creative";
        Track: {
            username: string;
            type: components["schemas"]["EventTypeEnum"];
            link?: number;
            referrer?: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    health_retrieve: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
        };
    };
    me_retrieve: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Me"];
                };
            };
        };
    };
    me_analytics_retrieve: {
        parameters: {
            query?: {
                days?: 30 | 7 | 90;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
        };
    };
    me_blocks_list: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Block"][];
                };
            };
        };
    };
    me_blocks_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["Block"];
                "application/x-www-form-urlencoded": components["schemas"]["Block"];
                "multipart/form-data": components["schemas"]["Block"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Block"];
                };
            };
        };
    };
    me_blocks_destroy: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description A unique integer value identifying this block. */
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description No response body */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    me_blocks_partial_update: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description A unique integer value identifying this block. */
                id: number;
            };
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["PatchedBlock"];
                "application/x-www-form-urlencoded": components["schemas"]["PatchedBlock"];
                "multipart/form-data": components["schemas"]["PatchedBlock"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Block"];
                };
            };
        };
    };
    me_blocks_reorder_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["Reorder"];
                "application/x-www-form-urlencoded": components["schemas"]["Reorder"];
                "multipart/form-data": components["schemas"]["Reorder"];
            };
        };
        responses: {
            /** @description No response body */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    me_education_list: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Education"][];
                };
            };
        };
    };
    me_education_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["Education"];
                "application/x-www-form-urlencoded": components["schemas"]["Education"];
                "multipart/form-data": components["schemas"]["Education"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Education"];
                };
            };
        };
    };
    me_education_destroy: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description A unique integer value identifying this education. */
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description No response body */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    me_education_partial_update: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description A unique integer value identifying this education. */
                id: number;
            };
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["PatchedEducation"];
                "application/x-www-form-urlencoded": components["schemas"]["PatchedEducation"];
                "multipart/form-data": components["schemas"]["PatchedEducation"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Education"];
                };
            };
        };
    };
    me_education_reorder_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["Reorder"];
                "application/x-www-form-urlencoded": components["schemas"]["Reorder"];
                "multipart/form-data": components["schemas"]["Reorder"];
            };
        };
        responses: {
            /** @description No response body */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    me_experience_list: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Experience"][];
                };
            };
        };
    };
    me_experience_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["Experience"];
                "application/x-www-form-urlencoded": components["schemas"]["Experience"];
                "multipart/form-data": components["schemas"]["Experience"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Experience"];
                };
            };
        };
    };
    me_experience_destroy: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description A unique integer value identifying this experience. */
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description No response body */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    me_experience_partial_update: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description A unique integer value identifying this experience. */
                id: number;
            };
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["PatchedExperience"];
                "application/x-www-form-urlencoded": components["schemas"]["PatchedExperience"];
                "multipart/form-data": components["schemas"]["PatchedExperience"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Experience"];
                };
            };
        };
    };
    me_experience_reorder_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["Reorder"];
                "application/x-www-form-urlencoded": components["schemas"]["Reorder"];
                "multipart/form-data": components["schemas"]["Reorder"];
            };
        };
        responses: {
            /** @description No response body */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    me_languages_list: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SpokenLanguage"][];
                };
            };
        };
    };
    me_languages_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SpokenLanguage"];
                "application/x-www-form-urlencoded": components["schemas"]["SpokenLanguage"];
                "multipart/form-data": components["schemas"]["SpokenLanguage"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SpokenLanguage"];
                };
            };
        };
    };
    me_languages_destroy: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description A unique integer value identifying this spoken language. */
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description No response body */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    me_languages_partial_update: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description A unique integer value identifying this spoken language. */
                id: number;
            };
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["PatchedSpokenLanguage"];
                "application/x-www-form-urlencoded": components["schemas"]["PatchedSpokenLanguage"];
                "multipart/form-data": components["schemas"]["PatchedSpokenLanguage"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SpokenLanguage"];
                };
            };
        };
    };
    me_languages_reorder_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["Reorder"];
                "application/x-www-form-urlencoded": components["schemas"]["Reorder"];
                "multipart/form-data": components["schemas"]["Reorder"];
            };
        };
        responses: {
            /** @description No response body */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    me_links_list: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Link"][];
                };
            };
        };
    };
    me_links_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["Link"];
                "application/x-www-form-urlencoded": components["schemas"]["Link"];
                "multipart/form-data": components["schemas"]["Link"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Link"];
                };
            };
        };
    };
    me_links_destroy: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description A unique integer value identifying this link. */
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description No response body */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    me_links_partial_update: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description A unique integer value identifying this link. */
                id: number;
            };
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["PatchedLink"];
                "application/x-www-form-urlencoded": components["schemas"]["PatchedLink"];
                "multipart/form-data": components["schemas"]["PatchedLink"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Link"];
                };
            };
        };
    };
    me_links_reorder_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["Reorder"];
                "application/x-www-form-urlencoded": components["schemas"]["Reorder"];
                "multipart/form-data": components["schemas"]["Reorder"];
            };
        };
        responses: {
            /** @description No response body */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    me_profile_retrieve: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Profile"];
                };
            };
        };
    };
    me_profile_partial_update: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["PatchedProfile"];
                "application/x-www-form-urlencoded": components["schemas"]["PatchedProfile"];
                "multipart/form-data": components["schemas"]["PatchedProfile"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Profile"];
                };
            };
        };
    };
    me_profile_avatar_update: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "multipart/form-data": components["schemas"]["ImageUpload"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Profile"];
                };
            };
        };
    };
    me_profile_avatar_destroy: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description No response body */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    me_projects_list: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Project"][];
                };
            };
        };
    };
    me_projects_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["Project"];
                "application/x-www-form-urlencoded": components["schemas"]["Project"];
                "multipart/form-data": components["schemas"]["Project"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Project"];
                };
            };
        };
    };
    me_projects_update: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description A unique integer value identifying this project. */
                id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["Project"];
                "application/x-www-form-urlencoded": components["schemas"]["Project"];
                "multipart/form-data": components["schemas"]["Project"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Project"];
                };
            };
        };
    };
    me_projects_destroy: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description A unique integer value identifying this project. */
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description No response body */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    me_projects_partial_update: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description A unique integer value identifying this project. */
                id: number;
            };
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["PatchedProject"];
                "application/x-www-form-urlencoded": components["schemas"]["PatchedProject"];
                "multipart/form-data": components["schemas"]["PatchedProject"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Project"];
                };
            };
        };
    };
    me_projects_image_update: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description A unique integer value identifying this project. */
                id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "multipart/form-data": components["schemas"]["ImageUpload"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Project"];
                };
            };
        };
    };
    me_projects_image_destroy: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description A unique integer value identifying this project. */
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description No response body */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    me_projects_reorder_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["Reorder"];
                "application/x-www-form-urlencoded": components["schemas"]["Reorder"];
                "multipart/form-data": components["schemas"]["Reorder"];
            };
        };
        responses: {
            /** @description No response body */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    me_skills_list: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Skill"][];
                };
            };
        };
    };
    me_skills_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["Skill"];
                "application/x-www-form-urlencoded": components["schemas"]["Skill"];
                "multipart/form-data": components["schemas"]["Skill"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Skill"];
                };
            };
        };
    };
    me_skills_destroy: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description A unique integer value identifying this skill. */
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description No response body */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    me_skills_partial_update: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description A unique integer value identifying this skill. */
                id: number;
            };
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["PatchedSkill"];
                "application/x-www-form-urlencoded": components["schemas"]["PatchedSkill"];
                "multipart/form-data": components["schemas"]["PatchedSkill"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Skill"];
                };
            };
        };
    };
    me_skills_reorder_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["Reorder"];
                "application/x-www-form-urlencoded": components["schemas"]["Reorder"];
                "multipart/form-data": components["schemas"]["Reorder"];
            };
        };
        responses: {
            /** @description No response body */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    profiles_retrieve: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                username: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PublicProfile"];
                };
            };
        };
    };
    track_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["Track"];
                "application/x-www-form-urlencoded": components["schemas"]["Track"];
                "multipart/form-data": components["schemas"]["Track"];
            };
        };
        responses: {
            /** @description No response body */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
}
